version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: Bidnow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    environment:
      DATABASE_URL: "postgresql://root:secret@postgres:5432/Bidnow?sslmode=disable"
      NODE_ENV: production
      AWS_REGION: sa-east-1
      AWS_S3_BUCKET: andrerimes
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8081:8081"
      - "3334:3334"
    depends_on:
      postgres:
        condition: service_healthy 
    networks:
      - app-network

  nestjs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs-dev
    environment:
      DATABASE_URL: "postgresql://root:secret@postgres:5432/Bidnow?sslmode=disable"
      NODE_ENV: development
      AWS_REGION: sa-east-1
      AWS_S3_BUCKET: andrerimes
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8081:8081"
      - "3334:3334"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy 
    networks:
      - app-network
    command: npm run start:dev
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge